export const GHL_CONFIG = {
    API_BASE_URL: "https://services.leadconnectorhq.com",
    ENDPOINTS: {
        TOKEN: "/oauth/token",
        USER: "/users/me",
        CONTACTS: "/contacts",
        OPPORTUNITIES: "/opportunities",
    },
    SCOPES: [
        "contacts.readonly",
        "contacts.write",
        "opportunities.readonly",
        "opportunities.write",
        "locations.readonly",
        "locations/customValues.readonly",
        "locations/customValues.write",
        "locations/customFields.readonly",
        "locations/customFields.write",
        "objects/schema.readonly",
        "objects/schema.write",
        "objects/record.readonly",
        "objects/record.write",
        "medias.readonly",
        "medias.write",
        "calendars.readonly",
        "calendars.write",
        "calendars/events.readonly",
        "calendars/events.write",
        "calendars/groups.readonly",
        "calendars/groups.write",
        "calendars/resources.readonly",
        "calendars/resources.write",
        "conversations.readonly",
        "conversations.write",
        "conversations/message.readonly",
        "conversations/message.write",
        "conversations/reports.readonly",
        "conversations/livechat.write",
        "users.readonly",
        "users.write",
        "documents_contracts/list.readonly",
        "documents_contracts/sendLink.write",
        "documents_contracts_template/list.readonly",
        "documents_contracts_template/sendLink.write"
    ]
};
