'use server';

import db from '@/lib/db';
import { revalidatePath } from 'next/cache';
import { runAgent } from '@/lib/ai/agent';
import { generateVisualId } from '@/lib/google/utils';

export async function analyzeContactAction(contactId: string, locationId: string) {
    try {
        console.log(`[analyzeContactAction] Running Autonomous Agent for ${contactId}...`);

        // 1. Fetch Contact & Conversation History
        const conversations = await db.conversation.findMany({
            where: { contactId, locationId },
            include: { messages: { orderBy: { createdAt: 'asc' }, take: 20 } },
            orderBy: { lastMessageAt: 'desc' },
            take: 1
        });

        let historyText = "";
        if (conversations.length > 0) {
            const conversation = conversations[0];
            historyText = conversation.messages.map(m =>
                `${m.direction === 'outbound' ? 'Agent' : 'Lead'}: ${m.body}`
            ).join("\n");
        } else {
            const contact = await db.contact.findUnique({ where: { id: contactId } });
            if (contact?.message) {
                historyText = `Lead Initial Message: ${contact.message}`;
            }
        }

        // 2. Run Autonomous Agent
        const agentResult = await runAgent(contactId, locationId, historyText);

        if (!agentResult.success) {
            return { success: false, message: agentResult.message || "Agent failed." };
        }

        // 3. Map Agent Result to UI Format (Compat Layer)
        // The Agent has already updated the DB (requirements, logs) via tools.
        // We just need to construct the return object for the UI dialog.

        // Improve: Fetch the updated contact to get the "Vision ID" generated by the tool updates + sync?
        // Actually, the UI expects `phoneContactEntry`, `requirements`, `drafts`, `crmSummary`.

        // We can just construct a summary from the Agent's thought process

        const contact = await db.contact.findUnique({ where: { id: contactId } });

        // Re-generate Visual ID string locally for display (it's already correct in DB potentially but good to show)
        // Need roles for exact ID
        const contactWithRoles = await db.contact.findUnique({
            where: { id: contactId },
            include: { propertyRoles: { include: { property: true } } }
        });

        const visualId = contactWithRoles ? generateVisualId(contactWithRoles) : "Updated Lead";

        return {
            success: true,
            data: {
                phoneContactEntry: {
                    firstName: contact?.name || "Lead",
                    lastName: visualId
                },
                requirements: {
                    // Just showing what's in DB now
                    status: contact?.requirementStatus,
                    district: contact?.requirementDistrict,
                    maxPrice: contact?.requirementMaxPrice
                },
                drafts: {
                    icebreaker: agentResult.draft || "No draft generated.",
                    qualifier: ""
                },
                crmSummary: agentResult.thought || "Agent executed actions."
            }
        };

    } catch (error) {
        console.error("analyzeContactAction failed:", error);
        return { success: false, message: "Failed to run analysis." };
    }
}
